platform :ios, '7.0'
#use_frameworks!

target 'PlayerDemo' do
  pod 'ASIHTTPRequest', '~> 1.8.2'
  pod 'CocoaHTTPServer', '~> 2.3'
end

target 'PlayerDemoTests' do
   pod 'ASIHTTPRequest', '~> 1.8.2'
end