platform :ios, '7.0'
#use_frameworks!

target 'PlayerDemo' do
  pod 'ASIHTTPRequest', '~> 1.8.2'
  pod 'CocoaHTTPServer', '~> 2.3'
#  pod 'kxmovie', '0.0.3' //不适用pod方式，以为要修改kxmovie里面的代码
end

target 'PlayerDemoTests' do
   pod 'ASIHTTPRequest', '~> 1.8.2'
end